[project]
name = "ex-basics-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
pammi-hello = "pammi_hello.main:app"